### ISSUE TITLE
enforce 50m minimum for trigger polygons?

### ISSUE THREAD

**Issue by ngoldman** [Esri/geotrigger-editor#197]
This should be easy for point+radius, not easy for polygons. The alternative would be to notify the user when their trigger boundary is too small and unlikely to be effective.

**Comment by ngoldman** [comment]
![](http://www.avatarsdb.com/avatars/american_flag_eagle.gif)

**Comment by jgravois** [comment]
motion to re-open :us: 
jgravois/geotrigger-editor#1
