### ISSUE TITLE
Needs tool to batch create triggers 

### ISSUE THREAD

**Issue by phpmaps** [Esri/geotrigger-editor#220]

**Comment by jgravois** [comment]
you mean like something that takes advantage of [this](https://developers.arcgis.com/geotrigger-service/guide/import-feature-service/)?

**Comment by ngoldman** [comment]
@jgravois that was an experimental script created by @patrickarlt a long time ago. not sure if it's still working 100%. worth investigating though.

**Comment by phpmaps** [comment]
@jgravois @patrickarlt @ngoldman   -   @jgravois 's link did not test well in real life experiments involving data analysts and marketing staff. if you guys want to chat about this I can get into details.   GTE needs builtin support for CSV, Shapefiles and Feature Services - big time.
