### ISSUE TITLE
I have issue during loading the trigger/list

### ISSUE THREAD

**Issue by jackhuang89** [Esri/geotrigger-editor#230]
![screen shot 2016-08-19 at 4 26 44 pm](https://cloud.githubusercontent.com/assets/3734296/17803565/c637d212-6629-11e6-92bc-fc547db4a48c.png)

Text :

`error :
{type: "invalidHeader", message: "invalid header or header value",…}
code :
400
headers :
{Authorization: [{type: "invalid", message: "Application creation is disabled"}]}
Authorization :
[{type: "invalid", message: "Application creation is disabled"}]
message :
"invalid header or header value"
type :
"invalidHeader"`

I capture this image from chrome console.

Application creation disabled

Any help about this?

I trying other request using node.js and xcode.

e.g. trigger/create

also tell me "Application creation disabled"

**Comment by jgravois** [comment]
hi @jackhuang89, thanks for reporting the problem.  You are encountering this problem because it is no longer possible to create a new ArcGIS Online item and use it to manager Geotriggers.

A public announcement with additional details will be posted online soon
https://developers.arcgis.com/features/geotrigger-service/

**Comment by jackhuang89** [comment]
It means I should stop to use geotrigger for demo because it is dead?

Oh... I need to tell someone about this.

**Comment by jackhuang89** [comment]
# Transfer GeoTrigger to GeoEvent

I used a old application for demo because the old one can create / update / delete trigger from editor.
For long term, I trying to use Geoevent to do the same thing.

But I am new to use geoevent.
I set as below: 
Input connector as "Receive JSON on a REST Endpoint"
Output connector as "Push JSON to an External Website"

Web service to push notification.

Here is my issue:
[http://server.arcgis.com/en/geoevent-extension/latest/process-event-data/processors.htm](http://server.arcgis.com/en/geoevent-extension/latest/process-event-data/processors.htm)

1. I don't really understand what is the logic of processors is doing the same thing as geotrigger.
---

What I got right now?
I got a feature layer contains points but without boundary of detect area.

---

I keep reading tutorials at this moment.
If anyone know the right direction to transfer geotrigger to geoevent, please tell me.

Thanks.

**Comment by jgravois** [comment]
if you haven't already, i suggest that you check out the [Introduction to GeoEvent](http://www.arcgis.com/home/item.html?id=b6a35042effd44ceab3976941d36efcf) tutorial.

for additional assistance migrating please consider using
* Esri Technical Support
* [GeoNet - GeoEvent](https://geonet.esri.com/community/gis/enterprise-gis/geoevent)
* GIS Stack Exchange
* posting an issue in a GitHub repository that pertains to the GeoEvent Extension for ArcGIS Server
